version: '3.7'

services:
  librarian:
    #build: . # Uncomment to build from source
    image: codeberg.org/librarian/librarian:latest
    user: 65534:65534
    read_only: true
    ports:
      - '127.0.0.1:3046:3000'
    volumes:
      - ./data/config.yml:/app/config.yml
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID