pipeline:
  restore:
    image: codeberg.org/video-prize-ranch/woodpecker-sftp-cache
    settings:
      name: go
      path: /go
      ssh_key:
        from_secret: ssh_key
      restore: true
      port: 2222
      user: root
      host: summer-resonance-9602.internal
      cache_path: /data/cache
    secrets: [ssh_key]
  build:
    image: quay.io/podman/stable
    commands:
      - podman manifest create multiarch-tmp
      - podman build -v /go:/go --tag codeberg.org/librarian/librarian:latest --manifest multiarch-tmp --platform linux/amd64 .
      - podman build -v /go:/go --tag codeberg.org/librarian/librarian:latest --manifest multiarch-tmp --platform linux/arm64 .
      - podman login codeberg.org --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - podman manifest push --all multiarch-tmp "docker://codeberg.org/librarian/librarian:latest"
    secrets: [docker_username, docker_password]
  upload:
    image: codeberg.org/video-prize-ranch/woodpecker-sftp-cache
    settings:
      name: go
      path: /go
      ssh_key:
        from_secret: ssh_key
      restore: true
      port: 2222
      user: root
      host: summer-resonance-9602.internal
      cache_path: /data/cache
    secrets: [ssh_key]